### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by SaraLHer** [IBM/watson-discovery-ui#117]
dear,I'm getting this error when trying to run npm start. I've updated npm and node to the latest versions. Any idea of what could be causing this?

C:\tools\nodejs\node-global\node_modules\watson-discovery-ui\node_modules\express-browserify\index.js:104
                                throw err;
                                ^
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! watson-discovery-ui@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the watson-discovery-ui@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\tools\nodejs\node-cache\_logs\2018-04-19T02_31_33_087Z-debug.log

thanks.

**Comment by stevemart** [comment]
I think this is related to the express-browsify and babelify libraries -- see https://github.com/babel/babelify/issues/103 and https://github.com/babel/babelify/issues/157 for similar errors.

**Comment by emilyJQ** [comment]
dear,the babel-preset-es2015 has been installed,but the error can not be solved

**Comment by Harti** [comment]
@rhagarty `babel-preset-es2015` has been marked as deprecated, even if it *did* work, I don't see it as a permanent solution.

**Comment by rhagarty** [comment]
considering this closed after last PR where packages were updated
