### ISSUE TITLE
API Endpoint

### ISSUE THREAD

**Issue by samppita** [IBM/watson-discovery-ui#121]
I am using Frankfurt API, so my application is not connecting with the Discovery service using my credentials. It is pointing to a different endpoint. Where can I change it? 
Thanks

**Comment by rhagarty** [comment]
@samppita - in the setup call for the Discovery service (https://github.com/IBM/watson-discovery-ui/blob/master/server/index.js#L52)

Add a new param -
```
'url': <new endpoint>
```

Let me know if that fixes it. If so, I can add another variable to env.sample and use it here if a value is entered by the user.

**Comment by amitmeel** [comment]
it's working if we add the pram :)
