### ISSUE TITLE
"Error fetching results"

### ISSUE THREAD

**Issue by rlykins** [IBM/watson-discovery-ui#124]
Hello,

I am working on getting the Watson Discovery UI setup to use my data set, however, a majority of the time when submitting a query I get the error within the UI which states "Error fetching results". When I submit the same query through the Discovery Tooling or using cURL commands I get proper answers. 

From the Developer Tools window the code seems to exit with the Error "TypeError: fragment.childNodes[1].childNodes is undefined" at line 516 in the main.js file. However, if I limit the results returned to 10 at line 451 in main.js I do not get this error and answers are returned, though they are not the best answers which I would expect.

Is this an issue that has been encountered, and are there any ways to properly fix the error I am experiencing. 

Thanks,

-R

**Comment by rhagarty** [comment]
@rlykins - I will take a look at this ASAP.

**Comment by rlykins** [comment]
I should have specified that this is only for Natural Language Query, Passage Search has given no issues.

**Comment by rhagarty** [comment]
@rlykins - did you modify the code? If not, can you email me your .env file so I can access your data set?
rich.hagarty@ibm.com
