### ISSUE TITLE
Deploy to IBM Cloud not working

### ISSUE THREAD

**Issue by sebacea** [IBM/watson-discovery-ui#125]
Hi, I am not able to deploy the app in IBM Cloud here is the log

[watson-discovery-ui-20180613140428118-log.txt](https://github.com/IBM/watson-discovery-ui/files/2098507/watson-discovery-ui-20180613140428118-log.txt)

**Comment by stevemart** [comment]
@sebacea can you run the `cf logs watson-discovery-ui-20180613140428118 --recent` command? Or go into the ibm cloud console and check the application logs, not the deployment logs.

i'm not seeing anything app specific in that log. I see a few warnings about the watson node library, but 

```
Stopping instance 21b082ac-ee72-4b65-9242-611b8c5f69ca
Successfully destroyed container

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 crashed
FAILED
Error restarting application: Start unsuccessful

TIP: use 'cf logs watson-discovery-ui-20180613140428118 --recent' for more information

Finished: FAILED
```

doesn't help much -- i hate to ask to restart it and try again, but can you do that?

**Comment by sebacea** [comment]
Hie Steve, I deleted the cloud foundry app and re-deploy it using the button in th github repository. The error changed (attached below) but after a second deployment of the same app it works!

Preparing to start the job...
Logging into Bluemix as user: "sebastian.cea@pucv.cl" 
Preparing the build artifacts...
Target: https://api.ng.bluemix.net
Creating service instance wdui-discovery-service in org sebastian.cea@pucv.cl / space dev as sebastian.cea@pucv.cl...
OK

Create in progress. Use 'cf services' or 'cf service wdui-discovery-service' to check operation status.
Using manifest file /home/pipeline/5593a8e0-4d37-489f-8124-43f55975b205/manifest.yml

Creating app watson-discovery-ui-20180613234207493 in org sebastian.cea@pucv.cl / space dev as sebastian.cea@pucv.cl...
OK

Creating route watson-discovery-ui-20180613234207493-precipitative-superabominableness.mybluemix.net...
OK

FAILED
Server error, status code: 400, error code: 210001, message: The route is invalid: host must be no more than 63 characters

Finished: FAILED

**Comment by scottdangelo** [comment]
We need to change manifest.yml so that:
`random-route: false`
