### ISSUE TITLE
Issue with Deployment

### ISSUE THREAD

**Issue by seansodhaibm** [IBM/watson-discovery-ui#135]
Hi Everyone! 

I tried deploying this to my IBM cloud account but for some reason, the Delivery Pipeline stage fails. I tried checking the logs in the Discovery Application to see if there were any errors that were occurring but there were no error messages. I even cleared all services and instances off of my Cloud Account and redeployed it and it still failed. 

Any guidance on this would be great!

Thanks!!

**Comment by rhagarty** [comment]
@seansodhaibm - 
I assume you just used the "Deploy to IBM Cloud Button"? I just tried it and it worked for me.
Was a discovery service created? 
Can you provide any logs (even if you see no errors)?

**Comment by rhagarty** [comment]
@seansodhaibm - can you check the disco service and see if the "airbnb-austin-data" collection was created? And have you tried re-starting the app?

**Comment by seansodhaibm** [comment]
@rhagarty This is the only thing that I see when I open up Discovery: 

<img width="1259" alt="screen shot 2018-09-26 at 10 09 49 am" src="https://user-images.githubusercontent.com/41637300/46085591-5cacdd80-c174-11e8-8c44-71cdde435e77.png">

I checked the application and it wasn't running. So when I pressed "Start App", I received this warning: 
<img width="812" alt="screen shot 2018-09-26 at 10 12 03 am" src="https://user-images.githubusercontent.com/41637300/46085896-13a95900-c175-11e8-9131-7b810fcc780a.png">


I did not know that there was a memory limit that a free user could hit? When I open the application, I still have another 256 MB. Maybe it is referring to another memory limit? 


<img width="1395" alt="screen shot 2018-09-26 at 10 14 44 am" src="https://user-images.githubusercontent.com/41637300/46085872-055b3d00-c175-11e8-8999-ba9e78175b92.png">


Kindly advise!!

**Comment by rhagarty** [comment]
Yes, there definitely are limits to memory and service instances with the free tier. I think the 'Lite' account cap is at 256.

You could bump that down to 256 and try again, but I haven't had much success running it below 512.

The other alternative it to run this locally and limit the number of airbnb records you add to Discovery. Once you get that running, you can `cf push` the app to the IBM Cloud.

**Comment by seansodhaibm** [comment]
@rhagarty So i dialed down the memory per instance to 256MB. I then restarted the application and it is now currently running. However, the Delivery Pipeline still fails...

<img width="1521" alt="screen shot 2018-09-26 at 1 42 41 pm" src="https://user-images.githubusercontent.com/41637300/46098388-43b32500-c192-11e8-8fe1-4f784c09e093.png">

**Comment by rhagarty** [comment]
@seansodhaibm - please try again with the latest release. It requires less memory and attempts to load fewer reviews.

**Comment by seansodhaibm** [comment]
Yep looks like it works!! Thanks Rich!
