### ISSUE TITLE
canot find dotenv

### ISSUE THREAD

**Issue by samaa** [IBM/watson-discovery-ui#152]
what is the reason for canot find dotenv in console

**Comment by rhagarty** [comment]
@samaa - can you provide some more info?
Can you provide the log file?
Where you using the "Deploy to IBM Cloud" button?

**Comment by samaa** [comment]
It is actually turned now to 

Invalid URI "%3Chttps://discovery-us-south.watsonplatform.net/regions/us-south/services/crn%3Av1%3Abluemix%3Apublic%3Adiscovery%3Aus-south%3Aa%2F436a1ef6158b405fb8fb64b28278eec1%3Aef5cd1c7-1517-416d-9ea3-765a807c8bc0%3A%3A%3E/v1/environments"

What is the correct URI to provide. I took the url in browser

**Comment by rhagarty** [comment]
see issue #154 for resolution
