### ISSUE TITLE
Insufficient credentials

### ISSUE THREAD

**Issue by Azrael543** [IBM/watson-discovery-ui#153]
Just put my credential into the file env.sample  and rename it on .env

but just got the following issue

`Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password, api_key, and iam_access_token.`

this is my .env file
```
DISCOVERY_URL=https://gateway-XXX.watsonplatform.net/discovery/api
DISCOVERY_ENVIRONMENT_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DISCOVERY_COLLECTION_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
DISCOVERY_APIKEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**Comment by stevemart** [comment]
@Azrael543 use `DISCOVERY_IAM_APIKEY` 

See https://github.com/IBM/watson-discovery-ui/blob/master/env.sample as an exemplar

**Comment by Azrael543** [comment]
Valid now all work , Thanks

**Comment by stevemart** [comment]
Thanks for confirming!
