### ISSUE TITLE
Prolem with local running

### ISSUE THREAD

**Issue by SBSsbs** [IBM/watson-discovery-ui#155]
Good morning 

I tried to run the application using my own collection with my own set of documents, however, when launching the command npm start It seems every thing is going good but I got this error message

Unhandled rejection TypeError: Cannot read property 'length' of undefined
    at C:\Users\user\Desktop\Projet FFA\watson-discovery-ui\lib\utils.js:133:41

**Comment by rhagarty** [comment]
Hello @SBSsbs 

While this code pattern tries to be somewhat generic, it does require the underlying dataset to have specific fields. At a minimum, it requires: `text`, `id`, `date`, and `title`. 

That error indicates that a `text` field does not exist in the data. Please look at one of the json files found in the `data/airbnb` directory for an example of the data used to feed the default discovery collection.
