### ISSUE TITLE
An unexpected error occurred while processing your document.

### ISSUE THREAD

**Issue by harikeshoodles** [IBM/watson-discovery-ui#156]
we  are getting following error while uploading document on Watson tried by API endpoints. 

Response 
```
{
  "document_id" : "cdb7c1ec-3c5e-462e-b721-ec098d9df2a0",
  "filename" : "filename.pdf",
  "file_type" : "pdf",
  "sha1" : "8f9fa3dd0382172131d5e47b860f30c68152bee4",
  "status" : "failed",
  "status_description" : "Document failed to be ingested and indexed",
  "notices" : [ {
    "notice_id" : "internal_error",
    "document_id" : "cdb7c1ec-3c5e-462e-b721-ec098d9df2a0",
    "created" : "2019-03-06T09:08:49.064Z",
    "severity" : "error",
    "step" : "pdf",
    "description" : "An unexpected error occurred while processing your document."
  } ]
}
```

Environment Details
Storage: 6.97 MB / 200 MB
Documents: 5 / 1,000
Collections: 1 / 2

**Comment by rhagarty** [comment]
Hello @harikeshoodles. Need to ask a couple questions:

- are you using the API on your own, or just running the app in this code pattern?
- this code pattern uses json files, and this is a pdf, which means you are using your own data. Correct?
- can you try and add the one document using the Discovery service tooling within IBM Cloud? (See Step #3 of the README for an example)

**Comment by rhagarty** [comment]
No response - closing.
