### ISSUE TITLE
deploy to IBM Cloud fails with 'Could not bind to service wdui-discovery-service'

### ISSUE THREAD

**Issue by ejodet** [IBM/watson-discovery-ui#162]
Issue found by an external customer and reproduced in DAL

steps to reproduce:
- go to https://github.com/IBM/watson-discovery-ui
- click the deploy to IBM Cloud button
- toolchain creation: select my org and space
- create the toolchain
- go to the pipeline overview page

expected: deploy completes OK
observed: deploy failed with:

```
Done uploading
OK
Binding service wdui-discovery-service to app watson-discovery-ui-20190610115059701 in org eric_jodet@fr.ibm.com / space dev as eric_jodet@fr.ibm.com...
FAILED
Could not bind to service wdui-discovery-service
Error: Server error, status code: 409, error code: 60016, message: An operation for service instance wdui-discovery-service is in progress.

Finished: FAILED
```

**Comment by ejodet** [comment]
please consider this one as a blocker as it prevents from deploying the app
+ bad customer experience

**Comment by edzai** [comment]
Thanks for the help @ejodet

**Comment by ejodet** [comment]
@sanjeevghimire - thanks for the quick reaction.
Please let me know when I can test if the problem is fixed in prod
(so I can update our customer)
Thanks

**Comment by sanjeevghimire** [comment]
@ejodet can you try now? Make sure you clean up all the services and app before you re-deploy.

**Comment by edzai** [comment]
Keenly waiting for @ejodet result

**Comment by ejodet** [comment]
@sanjeevghimire - verified / fixed
The app deployed as expected
![image](https://user-images.githubusercontent.com/19149727/59324558-aa0bb380-8cdf-11e9-8813-649a0bde9ea2.png)

Thanks for the quick reaction!

**Comment by edzai** [comment]
Hi, I dont know what I am doing wrongly. Still getting same error. 

Binding service wdui-discovery-service to app watson-discovery-ui-20190612071544377 in org edzai@tedsf.org / space dev as edzai@tedsf.org...
FAILED
Could not bind to service wdui-discovery-service
Error: Server error, status code: 409, error code: 60016, message: An operation for service instance wdui-discovery-service is in progress.

Finished: FAILED

even changed account to start with no services

**Comment by ejodet** [comment]
@edzai - please retry from zero.
- delete the toolchain that you were previously using
- go back to https://github.com/IBM/watson-discovery-ui
- click the deploy to IBM Cloud button
- verify that the app deployed OK

Ping me on Slack if still stuck.
Thanks

**Comment by ejodet** [comment]
@sanjeevghimire - discussed with @edzai on Slack.
It turns out that even re-starting from scratch,  @edzai is still unable to have the app deployed after toolchain creation.

It looks like there is a resource discover-ui that is stuck in "deletion in progress"
![image](https://user-images.githubusercontent.com/19149727/59339355-4fd11980-8d04-11e9-8aa1-584d33ab69e6.png)

@edzai tried to manually delete it but the UI claims:
```
Error


An error occurred performing the operation. Try again later.

Description:

An operation for service instance wdui-discovery-service is in progress. (CF-AsyncServiceInstanceOperationInProgress - 60016)
```

So, possibly, the initial issue was fixed - since I was able to have a successful deploy
However, @edzai is still stuck and unable to have the app deployed, up and running.

May you please either:
- re-open this issue and work with @edzai  to collect additional information, let him know how to delete the `wdui-discovery-service`
- extract a new issue from this one so as to delete the `wdui-discovery-service` for a successful deploy

**Comment by scottdangelo** [comment]
Also, please note that the "wdui-discovery-service is in progress" issue is often see during start up. Try re-deploying the app.
Please file a new issue if you have further problems. Thanks.

**Comment by ejodet** [comment]
@edzai did re-try to deploy? Did next deploys succeed?

**Comment by ejodet** [comment]
@sanjeevghimire - we determined why deploy was still failing for @edzai 
The wd-ui-discovery service created during the first attempt
could not be deleted (it has been pending deletion for 2 days)

@edzai  a new account then tried again.
Once service was provisioned, deploy was successful

In case someone faces the same issue, here are the step to overcome the ```An operation for service instance wdui-discovery-service is in progress``` problem:
1 - go to cloud.ibm.com and expand CF Services
2 - delete all instances of the wdui-discovery-service
3 - try to re-deploy: should fail because wdui-discovery-service is pending creation
4 - on cloud.ibm.com, wait for the service to be "provisioned"
5 - try to re-deploy: should complete OK
