### ISSUE TITLE
HI anyone can help me??

### ISSUE THREAD

**Issue by LabswITALCONSULTA** [IBM/watson-discovery-ui#173]
I have an application in nodejs that worked.
Then I created another application that had to be similar to the first one but when I created the other one suddenly the original one stopped working.
I deleted the new one.
the old one does not go and I have always been mistaken:an instance of the application has been stopped abnormally: APP & # x2F; PROC & # x2F; WEB: Exite.
the app use discovery.
when i click on the url i see: 503 service unavaible when i am lucky , and always i see error 404 that the url doesn't exist
PLS HELP MEEEEE

**Comment by rhagarty** [comment]
@LabswITALCONSULTA is your issue related to this code pattern? If so, please provide more details.

**Comment by LabswITALCONSULTA** [comment]
@rhagarty i dont see any code pattern in your ansnwer. do you mean to say that you want to see the application code?

**Comment by stevemar** [comment]
closing as off-topic
