### ISSUE TITLE
I am getting 422 credentials not found error. How to resolve this issue? 

### ISSUE THREAD

**Issue by sruthiprabakaran** [IBM/watson-discovery-ui#182]
![Untitled](https://user-images.githubusercontent.com/56290186/82726509-4b79f280-9d02-11ea-83f3-879f317c6410.jpg)

**Comment by rhagarty** [comment]
@sruthiprabakaran looks like your connection is stale. Try going back out to the main IBM Cloud dashboard and logging back in, then launch your Discovery instance again.

**Comment by bookmywingsicabs** [comment]
I am getting the same error and I tried logging back in an launching Discovery instance again. It still gives the same error. 
Please help.

**Comment by Hawk7069** [comment]
I am getting the same error. I have tried logging back in and launching my Discovery instance again. It still gives the same error.
Please help.

**Comment by rhagarty** [comment]
@Hawk7069 - I passed this on to the discovery team and they would like more info.

Can you tell me what region you created the instance in?
And can you send the full URL you used to get to that page?

**Comment by Hawk7069** [comment]
Hello, 
I have created the instance in Seoul region.
I used the Launch Watson Discovery Button to access the service.

**Comment by rhagarty** [comment]
@Hawk7069 - by full URL, I meant the URL to access your service. It would start with something similar to:
https://us-south.discovery.watson.cloud.ibm.com/regions/us-south/services/......

**Comment by Hawk7069** [comment]
@rhagarty Hi, Yes, my URL is as follows:
https://kr-seo.discovery.watson.cloud.ibm.com/regions/kr-seo/services/crn%3Av1%3Abluemix%3Apublic%3Adiscovery%3Akr-seo%3Aa%2Fb040b24d8f4d48be805d62ad2e5d5728%3A56f289db-144f-44ce-b58c-7e93be42b0df%3A%3A

**Comment by rhagarty** [comment]
@Hawk7069 no luck yet finding an obvious issue with your credentials. Can you try clearing your browser cache/cookies, or better yet, trying another browser?

**Comment by Hawk7069** [comment]
@rhagarty Sure, thanks. I'll try doing that and update if I keep getting the same issue.

**Comment by sruthiprabakaran** [comment]
Hi! I tried with another system and it worked. But shows the same error in
my laptop everytime.

**Comment by Hawk7069** [comment]
@rhagarty @sruthiprabakaran thanks for the help. As it turns out it worked perfectly fine when I accessed the service via another web browser.
