### ISSUE TITLE
Error: Insufficient credentials provided in constructor arguments. 

### ISSUE THREAD

**Issue by aniloj19** [IBM/watson-discovery-ui#185]
Need help. I can't deploy it locally - I just follow the guide. I created .env file and updated the credentials. 

Thanks! 

![image](https://user-images.githubusercontent.com/17064536/87907764-c4de5900-ca97-11ea-976c-a66c639b007c.png)

**Comment by rhagarty** [comment]
Hello @aniloj19 - I can try and help with this.

First off, your directory is "watson-discovery-food-reviews-master". Which code pattern are you working on - watson-discovery-ui or watson-discovery-food-reviews?

This looks like a typical "bad credentials" issue. Can you post your `.env` file? You can replace some of the characters with "XXX" to hide your sensitive info. I just want to make sure the format is correct and you included all of the fields.
