### ISSUE TITLE
When using Entity and Relation Extraction only, the watson-discovery-ui does not display any results

### ISSUE THREAD

**Issue by stevops** [IBM/watson-discovery-ui#189]
Hello,

we are trying to query Discovery using entity and relation extraction only. When using the AirBnB example and adding enrichments "Entity" and "Realation" only for the 999 sample docs included in watson-discovery-ui/data, then the Discovery UI correctly displays the number of entities / realtions found. For the example that is 

Person(625)
Facility(388)
GeopoliticalEntity(333)
EventCommunication(213)
Location(183)

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/13540461/99241285-efe67880-27fd-11eb-8dd7-2f4b9b4b9a1d.png">

However, when using the watson-discovery-ui to do a search, no results are displayed at all (without selecting any filter, the query result is empty). Also, when e.g. filtering by EntityType "Person", no results are displayed. Please note in the screenshot below, that the network tab displays the result JSON of the query. The full JSON is attached further below.

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/13540461/99241797-a3e80380-27fe-11eb-9354-61e60a7afe45.png">

So, in the Chrome Dev-Tools - if we use no filtering at all or use a simple filter for EntityType "Person" - we can see that Discovery responses with a JSON that includes e.g. Person entites and the text where the person is mentioned. Why are the results returned for Entity/Realtion extraction not displayed by the watson-discovery-ui? I.e. what do we need to do, in order to see Matches for both, an "empty" query and/or a query that filters by EntityType?

Please see the full response JSON for an empty/unfiltered search attached:

[test_query_response_json.json.txt](https://github.com/IBM/watson-discovery-ui/files/5545599/test_query_response_json.json.txt)

Thank you.

**Comment by rhagarty** [comment]
hello @stevops - and you are not seeing any errors in your server console?

I know that the discovery API changed the format of the returned data, so you could have an issue if you are using a newer version of the watson SDK than what is pinned in package.json.

Can you provide the output from your console where you ran "npm start"?

**Comment by stevops** [comment]
Hello @rhagarty ,

Thank you for your help. Indeed, the console logs an error. That is:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/13540461/99357703-a43ed800-28ac-11eb-9689-b59b8eff8371.png">

The error occurs in utils.js, line 133-141. There, it is being checked if the result data items contain a sentiment prop, which they do not, as we removed all enrichments in Discovery, except for Entity and Relation extraction:

`// insure this item is valid
    if (!dataItem.enriched_text ||
        !dataItem.enriched_text.sentiment ||
        !dataItem.enriched_text.sentiment.document) {
      console.log('Found bad result - no enrichments found: ');
      console.log('     dataItem.title: ' + dataItem.title);
      console.log('     dataItem.id: ' + dataItem.id);
      break;
    }`

Is the UI meant to be only working if sentiment is enabled in the Discovery enrichments? I can change this by removing the check for the sentiment check, however, am not sure if this breaks other parts of the application. A data item returned by the Discovery API looks like this: 

`{id: "a2bdf948c6fcf0f0d3898430dd3354ca", result_metadata: {…
    }, subject: "", caseRef: "244574", text: " Telefonat mit Herrn Fahrudin und Herrn Bukowski (…m 24.12.-27.12. und vom 31.12.-2.1.16 zum Vater. ", …
}caseRef: "244574"creationTime: "23-12-2015 12:12:28"docName: "CS03_ 039"enriched_text: entities: Array(9)0: confidence: 0.989644count: 1disambiguation: {subtype: Array(1)
}sentiment: {score: 0, label: "neutral"
}text: "Irandeutsch"type: "Person"__proto__: Object1: {count: 1, sentiment: {…
    }, text: "Vater", confidence: 0.949211, type: "Person", …
}2: {count: 1, sentiment: {…
    }, text: "Herrn Fahrudin", confidence: 0.923878, type: "Person", …
}3: {count: 2, sentiment: {…
    }, text: "Jungen", confidence: 0.880669, type: "Person", …
}4: {count: 1, sentiment: {…
    }, text: "31.12", confidence: 0.862226, type: "Datum", …
}5: {count: 1, sentiment: {…
    }, text: "24.12", confidence: 0.820199, type: "Datum", …
}6: {count: 1, sentiment: {…
    }, text: "Cousin", confidence: 0.779322, type: "Person", …
}7: {count: 1, sentiment: {…
    }, text: "Herrn Bukowski", confidence: 0.774444, type: "Person", …
}8: {count: 1, sentiment: {…
    }, text: "UZ", confidence: 0.416709, type: "Person", …
}length: 9__proto__: Array(0)relations: []__proto__: Objectextracted_metadata: {sha1: "c67ab423b924b664bcf199c98d2183a91aafd716", filename: "244574_utf8_CS03_ 039_CLEANED.json", file_type: "json"
}id: "a2bdf948c6fcf0f0d3898430dd3354ca"notesId: "-5658374255746744320"result_metadata: {score: 1
}subject: ""text: " Telefonat mit Herrn Fahrudin und Herrn Bukowski (Bezugsbetreuer Irandeutsch Haus 4 Idsteiner Straße Tel.: 0111 - 222222):   die UZ sprach die Umgangsregelung an, mit der Bitte sich einen persönlichen Eindruck über die Gegebenheiten vor Ort in der Whg des Onkels/Cousin von den Jungen zu machen. Dies sei laut Mitarbeiter zu den Feiertagen personell nicht möglich, es werde aber durch ihn im Januar gern nachgeholt. Die Jungen sollen vom 24.12.-27.12. und vom 31.12.-2.1.16 zum Vater. "__proto__: Object`

What is the solution to this? Do we need to include Sentiment enrichment in order for the app to work OOTB, and, will we need to customize the app in case we want to work with entity and relation extraction only?

Thanks

**Comment by rhagarty** [comment]
@stevops - yes,  the app needs sentiments and other enrichments to work correctly. The graph, pie chart, word cloud and ratings require them. The app was never designed to work with limited data, but feel free to fork the code and make the necessary changes. Out of curiosity, why do you want to limit the number of enrichments on the data set? Can't you just ignore that part of the UI?

**Comment by stevops** [comment]
@rhagarty Thanks for clarification. We will simply add the sentiment enrichments in Discovery in a first step and ignore the portions of the UI, that do relate to sentiment / do not relate to Entity/Relation extraction.

"Out of curiosity, why do you want to limit the number of enrichments on the data set" --> Well, our ratio was, that we should only annotate what is needed. We are not using sentiment in our use case.
